# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e22bdf90f2f7b15f77961bf79197de9972ddb05192e9effd38fa85ce4a5bf95a0abb21499d8243f8ee4b7de81502a423879713809c1296e2941b158b072101b

test:
  secret_key_base: 6574e8953d5b2546d958b9248eaddea26efb38b7e3939400b2ebbdb9d718ee5292856d8b0d1dfbdd938d702668a33c98ac33f449147ef79301bd40ee754f9d03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
